### ISSUE TITLE
Previous Transaction Outs - required?

### ISSUE THREAD

**Issue by ghost** [ccoincash/bchjs#1]
I'm attempting to sign a transaction on testnet using https://ccoin.cash/#sign but the second "Previous Transaction Outs" appears to be required.

My transaction already contains all of the required information:

```
010000000166909a9b5fee761294240e393cf8653823ec7291970870523941e3ac29a08c0f00000000b400473044022074ab24f1c5281c5469cf710a081a473ed7c4f16e0015ff3256b5c047f44eb843022016935b56936cb5989b7750c30aba2d3664baba041a061aafb9fb2037215f7778414c695221024a5f606cdd0e51e2c46084600d0727ae6cd6a14065594e367636698908eb4d0c21025dc3ea5714154895661abbdd41db799ec9acda94a58ad302b7bf5004adf776112103e341b1d50d3bef7d4975f4c3dba3d1d3c151c103197453eb8a12d18b10e81ba753aeffffffff0240a5ae02000000001976a9149666de90f18da87dcb3d61e7f30dda43ecbdd40d88aca0c44a00000000001976a91462191ee66cbf09540e83880761b156c3be8a0c8988ac00000000
```

Maybe I'm missing how Bitcoin Cash differs from Bitcoin in this regard as Coinbin doesn't require this second field.

**Comment by ccoincash** [comment]
Signing bitcoin cash transaction is a little different from bitcoin core. 

It need the script code and output amount of the unspent transaction which your transaction txins depend on. And the script and amount is not included in the raw transaction. 

So you must provide the unspent transaction script and amount for the offline signing. That is the "Previous Transaction Outs".
